# Generated by Django 5.1.7 on 2025-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='describe',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опишите вашу проблему'),
        ),
    ]
